require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "**/tmp/**/*"
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "**/node_modules/**/*"
    - test/**/*
    - spec/**/*
    - config/**/*
    - lib/**/*
    - deploy/**/*
