# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |_repo| "https://github.com/#{repo}.git" }

ruby '3.0.6'

gem 'bootsnap', require: false
gem 'carrierwave'
gem 'cpf_cnpj'
gem 'cssbundling-rails'
gem 'dry-validation-rails', '~> 0.1.1'
gem 'fog-aws'
gem 'ibge-ruby'
gem 'jbuilder'
gem 'jsbundling-rails'
gem 'mini_magick'
gem 'pg'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.2', '>= 7.0.2.3'
gem 'redis-rails'
gem 'sidekiq', '~> 7.2'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'trailblazer', '~> 2.1', '>= 2.1.3'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
