---
:concurrency: 5
:max_retries: 5
staging:
  :concurrency: 3
:queues:
  - [critical, 2]
  - [default, 1]

production:
  :concurrency: 5
  :queues:
    - [critical, 3]
    - [default, 2]

development:
  :concurrency: 3
:queues:
  - [critical, 2]
  - [default, 1]